data:
  all_annotations_txt: 'data/train.txt'
  # path to folder with frames extracted from videos
  data_folder: 'data/'
  # mean and std for normalization
  mean: [0.485, 0.456, 0.406]
  # Ratio of the dataset to be used for validation
  val_split_ratio: 0.2
  # Number of workers for data loading
  num_workers: 4

model:
  name: 'dual_stream'
  backbone: 'resnet50' # Changed from efficientnet-b4
  num_classes: 2
  # Set to 1 because we are using a default identity ID
  num_identities: 1 
  pretrained: True

train:
  batch_size: 32
  epochs: 50
  lr: 0.001
  optimizer: 'adam'
  scheduler: 'cosine'
  num_workers: 8
  # Early stopping patience
  patience: 5

# Loss configuration
loss:
  classification: 'focal_loss' # or 'bce'
  lambda_orthogonal: 0.1
  lambda_id: 0.5

# Logging
log:
  log_dir: 'logs/'
  log_interval: 100