# Data paths
data:
  train_dir: /path/to/train/data
  val_dir: /path/to/val/data
  test_dir: /path/to/test/data
  # lmdb_path: /path/to/lmdb

# Model selection
model:
  name: 'dual_stream' # or 'id_unaware'
  backbone: 'efficientnet-b4' # or 'resnet50', 'vit'
  pretrained: true

# Training parameters
train:
  batch_size: 32
  epochs: 50
  lr: 0.001
  optimizer: 'adam'
  scheduler: 'cosine'
  num_workers: 8
  # Early stopping patience
  patience: 5

# Loss configuration
loss:
  classification: 'focal_loss' # or 'bce'
  lambda_orthogonal: 0.1
  lambda_id: 0.5

# Logging
log:
  log_dir: 'logs/'
  log_interval: 100